<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Google Image Gallery Test</title>
        <link href='/css/magnific-popup.css' rel='stylesheet' type='text/css'>
        <link href='/css/style.css' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <form>
            <input type="text" name="query">
            <button>Search</button>
        </form>
        <div class="container">
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="/js/jquery.magnific-popup.min.js"></script>
        <script src="/js/script.js"></script>
    </body>
</html>
